# run the command below and set `local_backend: true` for local development
# npx netlify-cms-proxy-server
local_backend: true
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# publish_mode: editorial_workflow # didn't work when testing locally...
display_url: https://highlinekamouraska.netlify.app
logo_url: https://highlinekamouraska.netlify.app/images/hero.jpg
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  # - name: "blog" # Used in routes, e.g., /admin/collections/blog
  #   label: "Blog" # Used in the UI
  #   folder: "src/pages/cms/blog" # The path to the folder where the documents are stored
  #   create: true # Allow users to create new documents in this collection
  #   slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  #   fields: # The fields for each document, usually in front matter
  #     - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
  #     - {label: "Title", name: "title", widget: "string"}
  #     - {label: "Publish Date", name: "date", widget: "datetime"}
  #     - {label: "Featured Image", name: "thumbnail", widget: "image"}
  #     - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
  #     - {label: "Body", name: "body", widget: "markdown"}
  - name: "equipe"
    label: "Membre d'équipe"
    extension: "md"
    folder: "src/pages/equipe"
    create: true # Allow users to create new documents in this collection
    slug: "{{name}}"
    fields:
      - { name: "name", label: "nom", widget: "string" }
      - { name: "bio", label: "bio", widget: "markdown" }
      - { name: "order", label: "order", widget: "number" }
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
  - name: "homepage"
    label: "Homepage"
    extension: "md"
    folder: "src/pages/cms/accueil"
    create: false # Allow users to create new documents in this collection
    slug: "{{title}}"
    fields:
      - { name: "title", label: "Titre (<h1>)", widget: "string" }
      - { name: "text", label: "texte", widget: "markdown" }
  - name: "festival"
    label: "festival"
    extension: "md"
    folder: "src/pages/cms/festival"
    create: false # Allow users to create new documents in this collection
    slug: "{{name}}"
    fields:
      - { name: "title", label: "Titre (<h1>)", widget: "string" }
      - { name: "importantLinks", label: "Liens Important", widget: "markdown" }
      - { name: "cestQuoi", label: "C'est quoi un festival?", widget: "markdown" }
      - { name: "aSavoirT", label: " Titre pour section 'Choses à savoir'", widget: "string" }
      - { name: "feuT", label: "Feu - Titre", widget: "string" }
      - { name: "feuD", label: "Feu - Description", widget: "string" }
      - { name: "dechetT", label: "Déchêt - Titre", widget: "string" }
      - { name: "dechetD", label: "Déchêt - Description", widget: "string" }
      - { name: "parkingT", label: "Parking - Titre", widget: "string" }
      - { name: "parkingD", label: "Parking - Description", widget: "string" }
      - { name: "securiteT", label: "Securite - Titre", widget: "string" }
      - { name: "securiteD", label: "Securite - Description", widget: "string" }
      - { name: "respectT", label: "Respect - Titre", widget: "string" }
      - { name: "respectD", label: "Respect - Description", widget: "string" }
      - { name: "contributionT", label: "Contribution - Titre", widget: "string" }
      - { name: "contributionD", label: "Contribution - Description", widget: "string" }
        